#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config"
RASI="$DIR/rofi/runner.rasi"

# Run
rofi \
    -dpi 90 \
    -show run \
	-theme ${RASI}
