#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config"
RASI="$DIR/rofi/emoji.rasi"

# Run
rofi \
    -show emoji \
    -theme ${RASI}
